local FoodInfo = {
	["Ham"] = {
		Type = "Food",
		Sort = "Material",
		Desc = "If cooked right worth more than gold.",
		Stackable = true,
		Edible = true,
		Cookable = true,
		PickupAmount = 1,
		MaxDistance = 2,
		MaxStack = 10,
		HungerGain = 15,
		ReloadTime = 15,
		CookTime = {Done = 3, Burnt = 6},
	},
	["Cooked Ham"] = {
		Type = "Food",
		Sort = "Material",
		Desc = "Tasty cooked ham.",
		Stackable = true,
		Edible = true,
		Cookable = false,
		PickupAmount = 1,
		MaxDistance = 5,
		MaxStack = 15,
		HungerGain = 35,
		ReloadTime = 15,
	},
	["Burnt Ham"] = {
		Type = "Food",
		Sort = "Material",
		Desc = "A piece of ham gone to waste.",
		Stackable = true,
		Edible = true,
		Cookable = false,
		PickupAmount = 1,
		MaxDistance = 5,
		MaxStack = 15,
		HungerGain = 5,
		ReloadTime = 15,
	},
	["Watermelon"] = {
		Type = "Food",
		Sort = "Material",
		Desc = "Hydration and nutrients are important at sea.",
		Stackable = true,
		Edible = true,
		Cookable = false,
		PickupAmount = 1,
		MaxDistance = 5,
		MaxStack = 30,
		HungerGain = 6,
		ReloadTime = 5,
	},
	["Apple"] = {
		Type = "Food",
		Sort = "Material",
		Desc = "Hydration and nutrients are important at sea.",
		Stackable = true,
		Edible = true,
		Cookable = false,
		PickupAmount = 1,
		MaxDistance = 5,
		MaxStack = 30,
		HungerGain = 6,
		ReloadTime = 5,
	},
}

return FoodInfo
